### ISSUE TITLE
Importing theta-python as dependency

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#20]
I am using [poetry](https://python-poetry.org/) to manage my Python dependencies. Given that, and as **theta-python** is not available via [pypi](https://pypi.org/), I depend on using the `git` facilities in **poetry** to download and install it.

Turns out that as of today, **poetry** has no support for Python packages that don't have their configuration (`pyproject.toml`, `setup.cfg`, etc) at the root of the git repository.

Would it be possible to move the Python configuration files to the root? I am not proficient with `setup.cfg` and `setup.py`, but with `pyproject.toml` you would have something like:

```toml
[tool.poetry]
name = "theta-python"
version = "0.0.1"
description = "Support libraries for using Theta-IDL types in Python"
authors = ["Target"]
packages = [
    { include = "python/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.6.5"
hypothesis = "^6.36.1"
```
